version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 20 # default is 5

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: monthly
