name: Improve the docs.github.com site
description: Make a suggestion or report a problem about the technical implementation of docs.github.com.
labels:
  - content
body:
  - type: markdown
    attributes:
      value: |
        **HUBBERS!! THIS IS GITHUB/DOCS OPEN SOURCE REPO. OPEN AN ISSUE IN GITHUB/DOCS-CONTENT INSTEAD.**

        * For questions, ask in [Discussions](https://github.com/github/docs/discussions)
        * Before you file an issue read the [Contributing guide](https://github.com/github/docs/blob/main/CONTRIBUTING.md)
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/github/docs/issues)

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: textarea
    attributes:
      label: What article on docs.github.com is affected?
      description: |
        Include links to articles where you're seeing a problem, screenshots, what browser you're using, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What changes are you suggesting?
      description: |
        - Give as much detail as you can to help us understand the change you want to see. 
        - Why should the docs be changed? What use cases does it support? 
        - What is the expected outcome?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: |
        Any additional information, configuration, or data that might be necessary to reproduce the issue.
    validations:
      required: false
