name: Add docs-reviewers request to FR board

# **What it does**: Adds PRs in github/github that requested a review from docs-reviewers to the FR board
# **Why we have it**: To catch docs-reviewers requests in github/github
# **Who does it impact**: docs-content maintainers

on:
  workflow_dispatch:
  schedule:
    - cron: '25 4 * * *'

jobs:
  add-requests-to-board:
    name: Add requests to board
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo content
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Set up Python 3.9
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: |
          python .github/actions-scripts/fr-add-docs-reviewers-requests.py
        env:
          TOKEN: ${{ secrets.DOCS_BOT }}
