name: Pa11y

# **What it does**: Runs a static accessibility check on high traffic docs pages.
# **Why we have it**: We want accessibility support for the docs.
# **Who does it impact**: Docs engineering, users who need accessibility features.

on:
  workflow_dispatch:
  schedule:
    - cron: '25 17 * * *' # once a day at 17:25 UTC / 11:50 PST
jobs:
  test:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Setup Node
        uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm ci --include=optional

      - name: Run build scripts
        run: npm run build

      - name: Run pa11y tests
        run: npm run pa11y-test
