name: Send Crowdin PRs to boards

# **What it does**: Sends PRs opened on the crowdin branch to the ready for work column in this board: https://github.com/orgs/github/projects/1269#column-13447153
# **Why we have it**: To make sure the first responder sees crowdin translations that need to be merged as they review the Task board.
# **Who does it impact**: Docs localization and Docs Engineering

on:
  pull_request:
    types:
      - opened

jobs:
  triage:
    if: github.repository == 'github/docs-internal' && github.event.pull_request.head.ref == 'translations'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@626af12fe9a53dc2972b48385e7fe7dec79145c9
        with:
          github-token: ${{ secrets.DOCUBOT_READORG_REPO_WORKFLOW_SCOPES }}
          script: |
            var squadBoardColumnId = 13447153; // Add to the team task board

            try {
              await github.projects.createCard({
                column_id: squadBoardColumnId,
                content_id: context.payload.pull_request.id,
                content_type: "PullRequest"
              });
            } catch (error) {
              console.log(error);
            }
